### ISSUE TITLE
Give clay server the minimum k8s permissions

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/yinyo#51]
Right now it can do pretty much anything at a cluster level:
```
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
```
